name: ISW2 Testing

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    name: Test on JDK 11
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn -B clean test