name: ISW2 Testing

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    name: Test on JDK 11
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install EvoSuite Runtime
        run: |
          wget https://github.com/EvoSuite/evosuite/releases/download/v1.2.0/evosuite-standalone-runtime-1.2.0.jar
          mvn install:install-file -Dfile=evosuite-standalone-runtime-1.2.0.jar \
            -DgeneratePom=true \
            -DartifactId=evosuite-standalone-runtime \
            -DgroupId=org.evosuite \
            -Dversion=1.2.0 \
            -Dpackaging=jar

      - name: Cache SonarQube packages
          uses: actions/cache@v4
          with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                path: ~/.m2
                key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                restore-keys: ${{ runner.os }}-m2

      - name: Test with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=F-masci_openjpa \
          -Dsonar.coverage.jacoco.xmlReportPaths=coverage-reports/target/reports/jacoco-aggregate/jacoco.xml